spring:
  application:
    name: salary_management
  datasource:
    url: jdbc:mysql://localhost:3306/salary_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080